<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-83K3QJ4L" failures="0" tests="8" name="testcases.aiconfigsitepagetest" time="138.119" errors="1" timestamp="23 Jan 2022 06:59:28 GMT" skipped="7">
  <testcase classname="testcases.aiconfigsitepagetest" name="setup" time="138.119">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at testcases.aiconfigsitepagetest.setup(aiconfigsitepagetest.java:34)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:599)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setup -->
  <testcase classname="testcases.aiconfigsitepagetest" name="TC9" time="0.000">
    <skipped/>
  </testcase> <!-- TC9 -->
  <testcase classname="testcases.aiconfigsitepagetest" name="TC8" time="0.000">
    <skipped/>
  </testcase> <!-- TC8 -->
  <testcase classname="testcases.aiconfigsitepagetest" name="TC4">
    <skipped/>
  </testcase> <!-- TC4 -->
  <testcase classname="testcases.aiconfigsitepagetest" name="TC5">
    <skipped/>
  </testcase> <!-- TC5 -->
  <testcase classname="testcases.aiconfigsitepagetest" name="TC6">
    <skipped/>
  </testcase> <!-- TC6 -->
  <testcase classname="testcases.aiconfigsitepagetest" name="TC7">
    <skipped/>
  </testcase> <!-- TC7 -->
  <testcase classname="testcases.aiconfigsitepagetest" name="TC3">
    <skipped/>
  </testcase> <!-- TC3 -->
</testsuite> <!-- testcases.aiconfigsitepagetest -->
